@include('admin.components.common.head_admin')
@include('admin.components.common.header_admin')
@include('admin.components.common.nav_admin')
@yield('content')
@include('admin.components.common.scripts_admin')
